import type { TextStyle, TextStylePreset } from '../types/textStyle';

export const DEFAULT_TEXT_STYLE: TextStyle = {
  fontFamily: 'Arial',
  fontSize: 24,
  fontColor: '#ffffff',
  color: '#ffffff',
  fontWeight: 800,
  fontStyle: 'normal',
  textDecoration: 'none',
  textTransform: 'none',
  outlineColor: '#000000',
  outline: 2,
  outlineWidth: 2,
  shadowColor: '#000000',
  shadowOffsetX: 0,
  shadowOffsetY: 0,
  shadowBlur: 0,
  background: false,
  backgroundEnabled: false,
  backgroundColor: '#000000',
  backgroundOpacity: 0.55,
  backgroundRadius: 4,
  backgroundPaddingX: 8,
  backgroundPaddingY: 3,
  glowEnabled: false,
  glowColor: '#ffffff',
  glowBlur: 0,
  glowStrength: 0,
  letterSpacing: 0,
  lineHeight: 1.05,
  textAlign: 'center',
  opacity: 1,
  staticEffect: 'none',
};

const base = (style: TextStyle): TextStyle => ({
  ...DEFAULT_TEXT_STYLE,
  ...style,
  color: style.color || style.fontColor || DEFAULT_TEXT_STYLE.fontColor,
  fontColor: style.fontColor || style.color || DEFAULT_TEXT_STYLE.fontColor,
  outline: style.outline ?? style.outlineWidth ?? DEFAULT_TEXT_STYLE.outline,
  outlineWidth: style.outlineWidth ?? style.outline ?? DEFAULT_TEXT_STYLE.outline,
});

export const TEXT_STYLE_PRESETS: TextStylePreset[] = [
  { id: 'white-black-outline', name: 'White / Black Outline', previewText: 'Aa', style: base({ fontColor: '#ffffff', outlineColor: '#050505', outline: 4, fontWeight: 900 }) },
  { id: 'black-white-outline', name: 'Black / White Outline', previewText: 'Aa', style: base({ fontColor: '#080808', outlineColor: '#ffffff', outline: 4, fontWeight: 900 }) },
  { id: 'white-double-dark-outline', name: 'White / Double Dark Outline', previewText: 'Aa', style: base({ fontColor: '#ffffff', outlineColor: '#000000', outline: 5, secondaryOutlineColor: '#ffffff', secondaryOutlineWidth: 1, fontWeight: 900 }) },
  { id: 'white-soft-black-shadow', name: 'White / Soft Black Shadow', previewText: 'Aa', style: base({ fontColor: '#ffffff', outlineColor: '#111111', outline: 2, shadowColor: '#000000', shadowOffsetX: 2, shadowOffsetY: 3, shadowBlur: 3, fontWeight: 900 }) },
  { id: 'white-heavy-black-shadow', name: 'White / Heavy Black Shadow', previewText: 'Aa', style: base({ fontColor: '#ffffff', outlineColor: '#050505', outline: 3, shadowColor: '#000000', shadowOffsetX: 4, shadowOffsetY: 5, shadowBlur: 5, fontWeight: 900 }) },
  { id: 'yellow-black-outline', name: 'Yellow / Black Outline', previewText: 'Aa', style: base({ fontColor: '#fff000', outlineColor: '#030303', outline: 4, fontWeight: 900 }) },
  { id: 'red-white-outline', name: 'Red / White Outline', previewText: 'Aa', style: base({ fontColor: '#ff3338', outlineColor: '#ffffff', outline: 4, shadowColor: '#171717', shadowOffsetX: 1, shadowOffsetY: 1, shadowBlur: 1, fontWeight: 900 }) },
  { id: 'orange-white-outline', name: 'Orange / White Outline', previewText: 'Aa', style: base({ fontColor: '#ff7a18', outlineColor: '#ffffff', outline: 4, fontWeight: 900 }) },
  { id: 'blue-white-outline', name: 'Blue / White Outline', previewText: 'Aa', style: base({ fontColor: '#168fff', outlineColor: '#ffffff', outline: 4, fontWeight: 900 }) },
  { id: 'green-black-outline', name: 'Green / Black Outline', previewText: 'Aa', style: base({ fontColor: '#00f53a', outlineColor: '#000000', outline: 4, fontWeight: 900 }) },
  { id: 'black-light-gray-bg', name: 'Black / Light Gray Background', previewText: 'Aa', style: base({ fontColor: '#050505', outline: 0, background: true, backgroundEnabled: true, backgroundColor: '#cfcfcf', backgroundOpacity: 1, backgroundRadius: 7, backgroundPaddingX: 9, backgroundPaddingY: 4, fontWeight: 900 }) },
  { id: 'white-gray-bg', name: 'White / Gray Background', previewText: 'Aa', style: base({ fontColor: '#ffffff', outline: 0, background: true, backgroundEnabled: true, backgroundColor: '#9c9c9c', backgroundOpacity: 1, backgroundRadius: 7, backgroundPaddingX: 9, backgroundPaddingY: 4, fontWeight: 900 }) },
  { id: 'black-yellow-bg', name: 'Black / Yellow Background', previewText: 'Aa', style: base({ fontColor: '#000000', outline: 0, background: true, backgroundEnabled: true, backgroundColor: '#ffd900', backgroundOpacity: 1, backgroundRadius: 7, backgroundPaddingX: 9, backgroundPaddingY: 4, fontWeight: 900 }) },
  { id: 'white-purple-bg', name: 'White / Purple Background', previewText: 'Aa', style: base({ fontColor: '#ffffff', outline: 0, background: true, backgroundEnabled: true, backgroundColor: '#8c00ff', backgroundOpacity: 1, backgroundRadius: 7, backgroundPaddingX: 9, backgroundPaddingY: 4, fontWeight: 900 }) },
  { id: 'purple-white-bg', name: 'Purple / White Background', previewText: 'Aa', style: base({ fontColor: '#8c20ff', outline: 0, background: true, backgroundEnabled: true, backgroundColor: '#ffffff', backgroundOpacity: 1, backgroundRadius: 7, backgroundPaddingX: 9, backgroundPaddingY: 4, fontWeight: 900 }) },
  { id: 'black-white-bg', name: 'Black / White Background', previewText: 'Aa', style: base({ fontColor: '#000000', outline: 0, background: true, backgroundEnabled: true, backgroundColor: '#ffffff', backgroundOpacity: 1, backgroundRadius: 7, backgroundPaddingX: 9, backgroundPaddingY: 4, fontWeight: 900 }) },
  { id: 'white-black-bg', name: 'White / Black Background', previewText: 'Aa', style: base({ fontColor: '#ffffff', outline: 0, background: true, backgroundEnabled: true, backgroundColor: '#000000', backgroundOpacity: 1, backgroundRadius: 7, backgroundPaddingX: 9, backgroundPaddingY: 4, fontWeight: 900 }) },
  { id: 'green-black-bg', name: 'Green / Black Background', previewText: 'Aa', style: base({ fontColor: '#00f53a', outline: 0, background: true, backgroundEnabled: true, backgroundColor: '#000000', backgroundOpacity: 1, backgroundRadius: 7, backgroundPaddingX: 9, backgroundPaddingY: 4, fontWeight: 900 }) },
  { id: 'green-glitch', name: 'Green Glitch', previewText: 'Aa', style: base({ fontColor: '#00ff48', outlineColor: '#020202', outline: 2, shadowColor: '#111111', shadowOffsetX: 2, shadowOffsetY: 2, shadowBlur: 0, staticEffect: 'glitch', secondaryOutlineColor: '#ff1f7a', secondaryOutlineWidth: 2, fontWeight: 900 }) },
  { id: 'orange-red-duotone', name: 'Orange / Red Duotone', previewText: 'Aa', style: base({ fontColor: '#ffd21a', outlineColor: '#e02a34', outline: 2, shadowColor: '#e02a34', shadowOffsetX: 4, shadowOffsetY: 2, shadowBlur: 0, staticEffect: 'duotone', secondaryOutlineColor: '#e02a34', secondaryOutlineWidth: 3, fontWeight: 900 }) },
  { id: 'pink-red-glow', name: 'Pink / Red Glow', previewText: 'Aa', style: base({ fontColor: '#ffffff', outlineColor: '#ff2d6f', outline: 1, glowEnabled: true, glowColor: '#ff1f67', glowBlur: 10, glowStrength: 1.15, shadowColor: '#ff1f67', shadowBlur: 8, fontWeight: 900 }) },
  { id: 'yellow-glow', name: 'Yellow Glow', previewText: 'Aa', style: base({ fontColor: '#fff9c8', outlineColor: '#ffe600', outline: 1, glowEnabled: true, glowColor: '#ffe600', glowBlur: 11, glowStrength: 1.2, shadowColor: '#ffe600', shadowBlur: 8, fontWeight: 900 }) },
  { id: 'green-glow', name: 'Green Glow', previewText: 'Aa', style: base({ fontColor: '#efffff', outlineColor: '#35ff4d', outline: 1, glowEnabled: true, glowColor: '#35ff4d', glowBlur: 11, glowStrength: 1.2, shadowColor: '#35ff4d', shadowBlur: 8, fontWeight: 900 }) },
  { id: 'cyan-blue-glow', name: 'Cyan / Blue Glow', previewText: 'Aa', style: base({ fontColor: '#effcff', outlineColor: '#17dcff', outline: 1, glowEnabled: true, glowColor: '#17cfff', glowBlur: 11, glowStrength: 1.2, shadowColor: '#178bff', shadowBlur: 8, fontWeight: 900 }) },
];

export function textStylePresetById(id?: string) {
  return TEXT_STYLE_PRESETS.find((preset) => preset.id === id);
}
